default: &default
  adapter: postgresql
  host: localhost
  username: chris
  password: my_postgres
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: profile_development

production:
  <<: *default
  database: profile_production

development:
  <<: *default
  database: profile_development

production:
  <<: *default
  database: profile_production

test:
  <<: *default
  database: profile_test
<<<<<<< HEAD
 
staging:
  <<: *default
  database: profile_staging
=======

staging:
  <<: *default
  database: profile_staging
>>>>>>> 72ff0d659e8ac6dc46dc386ad5d1cb0f34a45ecd
