default: &default
  adapter: postgresql
  host: localhost
  username: chris
  password: postgres
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: profile_development

production:
  adapter: postgresql
  host: localhost
  username: chris
  password: postgres
  encoding: utf8
  database: profile_production

test:
  <<: *default
  database: profile_test

staging:
  <<: *default
  database: profile_staging
