default: &default
  host: localhost
  adapter: postgresql
  username: Chris
  password: postgres
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: development

production:
  <<: *default
  database: production

test:
  <<: *default
  database: test

staging:
  <<: *default
  database: staging
