default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: Chris

development:
  <<: *default
  database: profile_development

production:
  <<: *default
  database: profile_production

test:
  <<: *default
  database: profile_test

staging:
  <<: *default
  database: profile_staging