development:
  adapter: postgresql
  encoding: unicode
  database: profile_development
  pool: 5
  username: Chris

test:
  adapter: postgresql
  encoding: unicode
  database: profile_test
  pool: 5
  username: Chris

staging:
  adapter: postgresql
  encoding: unicode
  database: profile_staging
  pool: 5
  username: Chris